version: "3.5"

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - "mariadb:/var/lib/mysql"
    # networks:
    #   - backend
    restart: always

